# Generated by Django 2.2.10 on 2021-10-25 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADULTO',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='ATENCION_A_MUJER',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='CENTROS_POBLADOS',
            fields=[
                ('codigo_centro_poblado', models.IntegerField(primary_key=True, serialize=False)),
                ('COD_MUNICIPIO', models.IntegerField()),
                ('CODIGO', models.IntegerField()),
                ('CENTRO_POBLADO', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['codigo_centro_poblado'],
            },
        ),
        migrations.CreateModel(
            name='Datos_Integrante',
            fields=[
                ('identif', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoid', models.CharField(blank=True, max_length=100, null=True)),
                ('fnac', models.DateField(blank=True, max_length=2000, null=True)),
                ('paren', models.CharField(blank=True, max_length=100, null=True)),
                ('sx', models.CharField(blank=True, max_length=100, null=True)),
                ('gen', models.CharField(blank=True, max_length=100, null=True)),
                ('osex', models.CharField(blank=True, max_length=100, null=True)),
                ('ecivil', models.CharField(blank=True, max_length=100, null=True)),
                ('ocup', models.CharField(blank=True, max_length=100, null=True)),
                ('disc', models.CharField(blank=True, max_length=100, null=True)),
                ('etnia', models.CharField(blank=True, max_length=100, null=True)),
                ('victima', models.CharField(blank=True, max_length=100, null=True)),
                ('sgss', models.CharField(blank=True, max_length=100, null=True)),
                ('afi', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-identif'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['codigo_departamento'],
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('COD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='DISCAPACIDAD2',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='ESCOLARIDAD',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('COD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('COD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='GESTANTES',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='Grupo_Etnico',
            fields=[
                ('COD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='Hecho_Victimizante',
            fields=[
                ('COD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='INFECCIOSAS',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='MUNICIPIOS',
            fields=[
                ('CODIGO', models.IntegerField(primary_key=True, serialize=False)),
                ('MUNICIPIO', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['CODIGO'],
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('COD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='Orientacion_Sexual',
            fields=[
                ('COD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='PARENEZCOS',
            fields=[
                ('CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('PARENTEXCO', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-CODIGO'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre completo', max_length=200)),
                ('cedula', models.BigIntegerField(blank=True, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAZON_DE_ABANDONO_ESCOLAR',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='RIESGO_PARA_LA_INFANCIA',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='RIESGOS_PSICOSOCIALES',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='SALUD_ORAL',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='SEGURIDAD_ALIMENTARIA_Y_NUTRICIONAL',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('COD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Afiliacion',
            fields=[
                ('COD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Centro_Poblado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Ingrese el código del centro poblado', max_length=200)),
                ('tipo', models.CharField(help_text='Ingrese el tipo de centro poblado', max_length=200)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('simbolo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Ingrese el tipo de municipio', max_length=200)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('simbolo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Salida_De_Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Ingrese el tipo de salida de campo', max_length=200)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('requerimientos', models.CharField(blank=True, max_length=100, null=True)),
                ('simbolo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TIPOS_VIVIENDA',
            fields=[
                ('CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('TIPO', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-CODIGO'],
            },
        ),
        migrations.CreateModel(
            name='Vinculacion_SGSSS',
            fields=[
                ('COD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DETALLE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-COD'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('sitio', models.CharField(blank=True, max_length=4000, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=4000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=4000, null=True)),
                ('color', models.CharField(blank=True, help_text='Ingrese el color en formato Hexa', max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Salidas_De_Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, max_length=2000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=100000, null=True)),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Personal')),
                ('tipo_de_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Salida_De_Campo')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Zona')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('auxiliar_enfermeria_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria1', to='api.Personal')),
                ('auxiliar_enfermeria_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria2', to='api.Personal')),
                ('auxiliar_enfermeria_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria3', to='api.Personal')),
                ('auxiliar_enfermeria_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria4', to='api.Personal')),
                ('auxiliar_enfermeria_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria5', to='api.Personal')),
                ('auxiliar_enfermeria_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria6', to='api.Personal')),
                ('auxiliar_enfermeria_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria7', to='api.Personal')),
                ('enfermero_jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfermero_jefe', to='api.Personal')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medico', to='api.Personal')),
                ('psicologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psicologo', to='api.Personal')),
                ('tecnico_ambiental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico_ambiental', to='api.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Vivienda',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('DirVivienda', models.CharField(blank=True, max_length=100, null=True)),
                ('BarrioVivienda', models.CharField(blank=True, max_length=100, null=True)),
                ('GeoLocate', models.CharField(blank=True, max_length=100, null=True)),
                ('NombreRecibeVisita', models.CharField(blank=True, max_length=100, null=True)),
                ('TDRecibeVisita', models.CharField(blank=True, max_length=100, null=True)),
                ('IdentcoRecibeVisita', models.BigIntegerField(blank=True, null=True)),
                ('FnacRecibeVisita', models.DateField(blank=True, max_length=2000, null=True)),
                ('TelRecibeVisita', models.BigIntegerField(blank=True, null=True)),
                ('NombreOtroTipoVivienda', models.CharField(blank=True, max_length=100, null=True)),
                ('NroPersonasVivienda', models.IntegerField(blank=True, null=True)),
                ('NroDormitoriosVivienda', models.IntegerField(blank=True, null=True)),
                ('PerrosEnVivienda', models.IntegerField(blank=True, null=True)),
                ('GatosEnVivienda', models.IntegerField(blank=True, null=True)),
                ('OtrasMascotasEnVivienda', models.IntegerField(blank=True, null=True)),
                ('PerrosNoVacunEnVivienda', models.IntegerField(blank=True, null=True)),
                ('GatosNoVacunEnVivienda', models.IntegerField(blank=True, null=True)),
                ('TenenciaBovinos', models.IntegerField(blank=True, null=True)),
                ('TenenciaCaprinos', models.IntegerField(blank=True, null=True)),
                ('TenenciaOvinos', models.IntegerField(blank=True, null=True)),
                ('TenenciaPorcinos', models.IntegerField(blank=True, null=True)),
                ('TenenciaEquinos', models.IntegerField(blank=True, null=True)),
                ('TenenciaEMenores', models.IntegerField(blank=True, null=True)),
                ('TenenciaAExoticos', models.IntegerField(blank=True, null=True)),
                ('OtrosAnimalesTenencia', models.IntegerField(blank=True, null=True)),
                ('riesgoVivEV01', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivEV02', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivEV03', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivEV04', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivEV05', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivEV06', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivEV07', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivEV08', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCA01', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCA02', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCA03', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCA04', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivMA01', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivMA02', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivMA03', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivRS01', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivRS02', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivRS03', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivRS04', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivRS05', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivRS06', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivRS07', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivMP01', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivMP02', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivMP03', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivAH01', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivAH02', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivAH03', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivAH04', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivAH05', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCR01', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCR02', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCR03', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCR04', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCR05', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCR06', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCR07', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivCR08', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivNM01', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivNM02', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivNM03', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivNM04', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgoVivNM05', models.CharField(blank=True, max_length=100, null=True)),
                ('subsidioVivienda', models.CharField(blank=True, max_length=100, null=True)),
                ('CentroPoblado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CENTROS_POBLADOS')),
                ('MunicipioVivienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.MUNICIPIOS')),
                ('ParentezcoRecibeVisita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TIPOS_VIVIENDA')),
            ],
            options={
                'ordering': ['-uid'],
            },
        ),
        migrations.CreateModel(
            name='Datos_Riesgo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('op01', models.CharField(blank=True, max_length=100, null=True)),
                ('op02', models.CharField(blank=True, max_length=100, null=True)),
                ('op03', models.CharField(blank=True, max_length=100, null=True)),
                ('op04', models.CharField(blank=True, max_length=100, null=True)),
                ('op05', models.CharField(blank=True, max_length=100, null=True)),
                ('op06', models.CharField(blank=True, max_length=100, null=True)),
                ('op07', models.CharField(blank=True, max_length=100, null=True)),
                ('op08', models.CharField(blank=True, max_length=100, null=True)),
                ('op09', models.CharField(blank=True, max_length=100, null=True)),
                ('op10', models.CharField(blank=True, max_length=100, null=True)),
                ('op11', models.CharField(blank=True, max_length=100, null=True)),
                ('identif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Datos_Integrante')),
            ],
            options={
                'ordering': ['-identif'],
            },
        ),
        migrations.AddField(
            model_name='datos_integrante',
            name='vivienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Datos_Vivienda'),
        ),
        migrations.CreateModel(
            name='Calendario_Salidas_De_Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, max_length=2000, null=True)),
                ('fecha_fin', models.DateField(blank=True, max_length=2000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=100000, null=True)),
                ('tipo_de_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Salida_De_Campo')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Zona')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
