# Generated by Django 2.2.10 on 2021-05-25 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre completo', max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Salida_De_Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Ingrese el tipo de salida de campo', max_length=200)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('requerimientos', models.CharField(blank=True, max_length=100, null=True)),
                ('simbolo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('sitio', models.CharField(blank=True, max_length=4000, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=4000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=4000, null=True)),
                ('color', models.CharField(blank=True, help_text='Ingrese el color en formato Hexa', max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Salidas_De_Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, max_length=2000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=100000, null=True)),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Personal')),
                ('tipo_de_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Salida_De_Campo')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Zona')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Calendario_Salidas_De_Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, max_length=2000, null=True)),
                ('fecha_fin', models.DateField(blank=True, max_length=2000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=100000, null=True)),
                ('tipo_de_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Salida_De_Campo')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Zona')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
