# Generated by Django 2.2.10 on 2021-05-28 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210527_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='cargo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='auxiliar_enfermeria_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria1', to='api.Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='auxiliar_enfermeria_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria2', to='api.Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='auxiliar_enfermeria_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria3', to='api.Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='auxiliar_enfermeria_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria4', to='api.Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='auxiliar_enfermeria_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria5', to='api.Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='auxiliar_enfermeria_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria6', to='api.Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='auxiliar_enfermeria_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar_enfermeria7', to='api.Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='enfermero_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfermero_jefe', to='api.Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medico', to='api.Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psicologo', to='api.Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tecnico_ambiental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico_ambiental', to='api.Personal'),
        ),
    ]
