# Generated by Django 2.2.10 on 2021-06-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210528_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['codigo_departamento'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Centro_Poblado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Ingrese el código del centro poblado', max_length=200)),
                ('tipo', models.CharField(help_text='Ingrese el tipo de centro poblado', max_length=200)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('simbolo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Ingrese el tipo de municipio', max_length=200)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('simbolo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Departamento')),
                ('tipo_municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Municipio')),
            ],
            options={
                'ordering': ['codigo_municipio'],
            },
        ),
        migrations.CreateModel(
            name='Centro_Poblado',
            fields=[
                ('codigo_centro_poblado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_centro_poblado', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Municipio')),
                ('tipo_centro_poblado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Centro_Poblado')),
            ],
            options={
                'ordering': ['codigo_centro_poblado'],
            },
        ),
    ]
