# Generated by Django 2.2.10 on 2021-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_centro_poblado_departamento_municipio_tipo_centro_poblado_tipo_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_municipio',
            name='simbolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
