# Generated by Django 2.2.10 on 2021-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210615_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_centro_poblado',
            name='simbolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
