# Generated by Django 2.2.10 on 2021-09-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_datos_vivienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_vivienda',
            name='nro_ficha',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
