# Generated by Django 2.2.10 on 2021-09-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210917_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Integrante',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoid', models.CharField(blank=True, max_length=100, null=True)),
                ('identif', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fnac', models.DateField(blank=True, max_length=2000, null=True)),
                ('paren', models.CharField(blank=True, max_length=100, null=True)),
                ('sx', models.CharField(blank=True, max_length=100, null=True)),
                ('gen', models.CharField(blank=True, max_length=100, null=True)),
                ('osex', models.CharField(blank=True, max_length=100, null=True)),
                ('ecivil', models.CharField(blank=True, max_length=100, null=True)),
                ('ocup', models.CharField(blank=True, max_length=100, null=True)),
                ('disc', models.CharField(blank=True, max_length=100, null=True)),
                ('etnia', models.CharField(blank=True, max_length=100, null=True)),
                ('victima', models.CharField(blank=True, max_length=100, null=True)),
                ('sgss', models.CharField(blank=True, max_length=100, null=True)),
                ('afi', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-identif'],
            },
        ),
        migrations.CreateModel(
            name='Datos_Riesgo',
            fields=[
                ('identif', models.BigIntegerField(primary_key=True, serialize=False)),
                ('op01', models.CharField(blank=True, max_length=100, null=True)),
                ('op02', models.CharField(blank=True, max_length=100, null=True)),
                ('op03', models.CharField(blank=True, max_length=100, null=True)),
                ('op04', models.CharField(blank=True, max_length=100, null=True)),
                ('op05', models.CharField(blank=True, max_length=100, null=True)),
                ('op06', models.CharField(blank=True, max_length=100, null=True)),
                ('op07', models.CharField(blank=True, max_length=100, null=True)),
                ('op08', models.CharField(blank=True, max_length=100, null=True)),
                ('op09', models.CharField(blank=True, max_length=100, null=True)),
                ('op10', models.CharField(blank=True, max_length=100, null=True)),
                ('op11', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-identif'],
            },
        ),
    ]
